'use client'

import { useState } from 'react'
import { Download } from 'lucide-react'
import { Button } from '@/components/ui/button'

export default function PdfExportButton({ targetId, filename = 'pluto-report' }) {
  const [loading, setLoading] = useState(false)

  async function handleExport() {
    setLoading(true)
    try {
      const [{ default: jsPDF }, { default: html2canvas }] = await Promise.all([
        import('jspdf'),
        import('html2canvas'),
      ])

      const element = document.getElementById(targetId)
      if (!element) return

      // Temporarily expand element for clean capture
      const prevBg = element.style.backgroundColor
      element.style.backgroundColor = '#0a0a0a'

      const canvas = await html2canvas(element, {
        scale: 2,
        useCORS: true,
        backgroundColor: '#0a0a0a',
        logging: false,
      })

      element.style.backgroundColor = prevBg

      const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
      const pageW = pdf.internal.pageSize.getWidth()
      const pageH = pdf.internal.pageSize.getHeight()
      const imgW = pageW
      const imgH = (canvas.height * imgW) / canvas.width

      // Add Pluto branding header
      pdf.setFillColor(8, 8, 8)
      pdf.rect(0, 0, pageW, 10, 'F')
      pdf.setTextColor(200, 200, 200)
      pdf.setFontSize(8)
      pdf.text('Generated by Pluto Analytics Suite · plutommc.com', pageW / 2, 6.5, { align: 'center' })

      let posY = 12
      const remainingH = pageH - posY

      if (imgH <= remainingH) {
        pdf.addImage(canvas.toDataURL('image/png'), 'PNG', 0, posY, imgW, imgH)
      } else {
        // Multi-page: slice canvas
        const totalPages = Math.ceil(imgH / remainingH)
        for (let page = 0; page < totalPages; page++) {
          if (page > 0) pdf.addPage()
          const srcY = page * (remainingH / imgH) * canvas.height
          const srcH = Math.min((remainingH / imgH) * canvas.height, canvas.height - srcY)

          const pageCanvas = document.createElement('canvas')
          pageCanvas.width = canvas.width
          pageCanvas.height = srcH
          const ctx = pageCanvas.getContext('2d')
          ctx.drawImage(canvas, 0, srcY, canvas.width, srcH, 0, 0, canvas.width, srcH)
          pdf.addImage(pageCanvas.toDataURL('image/png'), 'PNG', 0, page === 0 ? posY : 0, imgW, (srcH / canvas.height) * imgH)
        }
      }

      pdf.save(`${filename}-${new Date().toISOString().slice(0, 10)}.pdf`)
    } catch (e) {
      console.error('PDF export failed:', e)
    } finally {
      setLoading(false)
    }
  }

  return (
    <Button variant="outline" size="sm" onClick={handleExport} disabled={loading}>
      <Download size={14} className="mr-1.5" />
      {loading ? 'Exporting...' : 'Export PDF'}
    </Button>
  )
}
